user_name=input("🌟 What's your name, awesome developer? ")
age=int(input("🎂 How old are you? "))
hobby=input("💻 What's your favorite programming language or tech hobby? ")
experience=input("📚 How many years of coding experience do you have? ")
goal=input("🎯 What's your biggest coding goal for this year? ")
company=input("🏢 What company or organization would you like to work for? ")
project=input("🚀 What's one cool project idea you'd like to build? ")

print("\n" + "="*60)
print(f"✨ Welcome {user_name}!")
print("="*60)
print(f"🎂 Age: {age} years old")
print(f"💻 Tech Hobby: {hobby}")
print(f"📚 Experience: {experience} years")
print(f"🎯 Goal: {goal}")
print(f"🏢 Dream Company: {company}")
print(f"🚀 Cool Project: {project}")
print("="*60)
print(f"Best of luck on your coding journey, {user_name}! 🚀💡")